import { chromium } from 'playwright-core';
const [,, file, out, w, h, scale] = process.argv;
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--allow-file-access-from-files'] });
const p = await b.newPage({ viewport:{width:+w,height:+h}, deviceScaleFactor:+(scale||1) });
p.on('console', m => console.log('console:', m.text()));
p.on('pageerror', e => console.log('pageerror:', e.message));
await p.goto(file.startsWith('http') ? file : 'file://' + process.cwd() + '/' + file);
await p.evaluate(() => document.fonts.ready);
await p.waitForFunction(() => window.DONE !== false, null, { timeout: 600000 });
await p.screenshot({ path: out });
await b.close();
